version: '3'

services:
  api:
    build: flask_api
    command: ["flask", "run", "--host=0.0.0.0"]
    volumes:
      - ./flask_api:/backend
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    ports:
      - "5000:5000"

  nojsxclient:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - '80:80'
    depends_on:
      - api

